/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Ajuda: typeof import('./src/components/Ajuda.vue')['default']
    AppFooter: typeof import('./src/components/AppFooter.vue')['default']
    Cadastros: typeof import('./src/components/Cadastros.vue')['default']
    ComoFunciona: typeof import('./src/components/comoFunciona.vue')['default']
    CTA: typeof import('./src/components/CTA.vue')['default']
    Footer: typeof import('./src/components/Footer.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    Home: typeof import('./src/components/Home.vue')['default']
    NavHeader: typeof import('./src/components/NavHeader.vue')['default']
    Preloader: typeof import('./src/components/preloader.vue')['default']
    RespostasAtivas: typeof import('./src/components/RespostasAtivas.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
}
